version: '3.1'

services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toutdoux
    ports:
       - '3306:3306'
    expose:
       - '3306'
    volumes:
       - db:/var/lib/mysql

volumes:
   db: