version: '3.1'

services:
  app:
    build: .
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/toutdoux
      SPRING_DATASOURCE_USERNAME: app
      SPRING_DATASOURCE_PASSWORD: app
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toutdoux
    ports:
       - '3306:3306'
    expose:
       - '3306'
    volumes:
       - db:/var/lib/mysql
    networks:
      - app-network

volumes:
   db:

networks:
  app-network: